version: '3.6'

services: 
    # backend api
    smart-brain-api:
        container_name: backend
        build: ./
        working_dir: /usr/src/smart-brain-api
        environment:
            POSTGRES_USER: clau
            POSTGRES_PASSWORD: clau
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        links:
            - postgres
        ports:
            - "3000:3000"
        command: npm start
        volumes:
            - ./:/usr/src/smart-brain-api
        

    # postgress
    postgres:
        environment:
            POSTGRES_USER: clau
            POSTGRES_PASSWORD: clau
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        build: ./postgres
        ports:
            - "5432:5432"